import Image from "next/image";
import Link from "next/link";

const highlights = [
  ["一站整理", "把校內零碎的活動、獎學金、實習與徵才資訊收進同一個入口。"],
  ["個人化篩選", "依系所、校區、興趣與截止日，快速找到真正相關的機會。"],
  ["可信任社群", "校友可驗證身分、發布職缺與活動；學生也能保有隱身選擇。"],
];

export default function DemoPage() {
  return <main className="min-h-screen bg-[#fffafa] text-[#2a1618]"><header className="border-b border-rose-100 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><Image src="/linkin-logo.png" width={42} height={42} alt="東吳 LinkIn" /><div><p className="font-bold text-[#8f1024]">東吳 LinkIn</p><p className="text-xs text-stone-500">合作夥伴展示版</p></div></div><Link href="/" className="rounded-lg border border-rose-200 px-4 py-2 text-sm font-semibold text-[#8f1024] hover:bg-rose-50">進入產品 Demo →</Link></div></header>
    <section className="bg-[#a5162a] text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div><p className="text-sm font-bold tracking-[0.2em] text-rose-100">SCU LINKIN · MVP</p><h1 className="mt-4 text-4xl font-bold leading-tight sm:text-6xl">把校園資訊，<br />轉成每個人的下一個機會。</h1><p className="mt-6 max-w-xl text-lg leading-8 text-rose-50">東吳 LinkIn 是串連學生、校友、企業與校內單位的校園機會平台。從資訊導引開始，逐步建立可被信任的人才與社群網絡。</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/" className="rounded-xl bg-white px-5 py-3 font-bold text-[#8f1024] hover:bg-rose-50">操作機會中心</Link><Link href="/profile" className="rounded-xl border border-rose-200 px-5 py-3 font-bold hover:bg-[#8f1024]">查看個人檔案</Link></div></div><div className="rounded-3xl bg-white p-6 text-[#2a1618] shadow-2xl"><p className="text-sm font-bold tracking-wider text-[#a5162a]">MVP 已具備</p><div className="mt-5 space-y-4"><Metric value="3" label="資訊類型：活動、獎學金、實習／徵才" /><Metric value="4" label="篩選維度：關鍵字、類別、系所、校區／截止日" /><Metric value="1" label="可信任資料來源與管理發布流程" /></div></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16"><p className="text-sm font-bold tracking-[0.16em] text-[#a5162a]">WHY NOW</p><h2 className="mt-3 text-3xl font-bold text-[#8f1024]">目前的校園資訊，難找、難比對，也難被有效連結。</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{highlights.map(([title, text], index) => <article key={title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-stone-200"><p className="text-sm font-bold text-[#a5162a]">0{index + 1}</p><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></article>)}</div></section>
    <section className="border-y border-rose-100 bg-white"><div className="mx-auto max-w-6xl px-5 py-16"><p className="text-sm font-bold tracking-[0.16em] text-[#a5162a]">DEMO FLOW</p><h2 className="mt-3 text-3xl font-bold text-[#8f1024]">三分鐘看見產品如何運作</h2><div className="mt-8 grid gap-4 md:grid-cols-3"><Step number="1" title="設定個人背景" text="填入系所、學制、興趣與經歷；可選擇隱身模式。" href="/profile" action="開啟個人檔案" /><Step number="2" title="探索適合的機會" text="用關鍵字與篩選器找到活動、獎學金與實習。" href="/" action="開啟機會中心" /><Step number="3" title="由單位維護可信資訊" text="透過管理後台建立、審核與更新發布內容。" href="/admin" action="開啟管理後台" /></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-16"><div className="rounded-3xl bg-stone-900 p-8 text-white sm:p-12"><p className="text-sm font-bold tracking-[0.16em] text-rose-200">NEXT PHASE</p><h2 className="mt-3 text-3xl font-bold">從資訊平台，走向東吳的可信任人才網絡。</h2><div className="mt-7 grid gap-4 md:grid-cols-3"><Next text="校友社群：貼文、活動與徵才發布" /><Next text="企業端：驗證後的職缺發布與人才接觸" /><Next text="LINE：依興趣與截止日的個人化推播" /></div></div></section>
  </main>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="flex gap-4 rounded-2xl bg-rose-50 p-4"><span className="text-3xl font-bold text-[#a5162a]">{value}</span><p className="self-center text-sm leading-6 text-stone-700">{label}</p></div>; }
function Step({ number, title, text, href, action }: { number: string; title: string; text: string; href: string; action: string }) { return <article className="rounded-2xl border border-stone-200 p-6"><span className="grid size-9 place-items-center rounded-full bg-[#a5162a] font-bold text-white">{number}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 min-h-14 leading-7 text-stone-600">{text}</p><Link href={href} className="mt-5 inline-block font-bold text-[#a5162a] hover:underline">{action} →</Link></article>; }
function Next({ text }: { text: string }) { return <p className="rounded-xl border border-stone-700 p-4 leading-7 text-stone-200">{text}</p>; }
